#!/usr/bin/env bash
# scripts/setup-dev-env.sh — dev only env bootstrap (NOT idempotent with .env.local).
#
# 问题: 'auto-explainer-saas' dev mode 需要 CREATOMATE_API_KEY / ANTHROPIC_API_KEY
# 等必填字段, lib/env.ts schema 在 server 启动时 validate. 如果 user 只
# cp .env.example .env.local 而没填值, 所有 key value 都是空 → getEnv() 抛
# 'Required' → server crash / route 永远 500 / '点击开始生成没反应'.
#
# 此脚本:
#   1. 备份现有 .env.local (如果存在)
#   2. 写入一个 **dev-safe placeholder** 值, 通过 schema (.min(N)) 验证
#   3. Real LLM / Render 仍需真 key 调用 (anthropic / creatomate API 真发 401
#      会看到, 但** server 自身能起来** + click-button 流程能跑)
#
# 用法 (从仓库根):
#   bash scripts/setup-dev-env.sh
#
# 之后:
#   npm run dev
#   浏览器 → http://localhost:3000
#   click 开始生成 → POST 201 → auto-redirect → status page polling

set -euo pipefail

cd "$(dirname "$0")/.."

if [ ! -f .env.example ]; then
  echo "❌ .env.example 不存在 — 仓库可能 broken"
  exit 1
fi

if [ -f .env.local ]; then
  ts="$(date +%Y%m%d%H%M%S)"
  cp .env.local ".env.local.bak.${ts}"
  echo "📦 已备份现有 .env.local → .env.local.bak.${ts}"
fi

# 用 .env.example 作骨架, 但有 placeholder value 太短不能让 schema .min(10) 通过.
# 这里**重写** env.local, 把所有 required key 塞 placeholder (符合 .min(10)) + optional 留空.
cat > .env.local << 'EOF'
# auto-generated by scripts/setup-dev-env.sh (dev-only)
# Real LLM / Render 仍需要真 key 调用 — placeholder 仅让 server 启动 + 能 click button.

# === Required (schema validate) ===
DATABASE_URL=postgres://postgres:postgres@localhost:5432/aesaas
REDIS_URL=redis://localhost:6379
ANTHROPIC_API_KEY=sk-ant-dev-placeholder-key-1234567890
CREATOMATE_API_KEY=creato-dev-placeholder-key-1234567890
BASIC_AUTH_USER=admin
BASIC_AUTH_PASS=dev-password-placeholder

# === Defaults (optional, lib/env.ts schema 已 default 这些) ===
NODE_ENV=development
LOG_LEVEL=info

# === Optional (留空 = 跳过对应功能) ===
# Azure Speech TTS — 留空则 phaseEncodeCreatomate 跳过 audio 注入
AZURE_SPEECH_KEY=
AZURE_SPEECH_REGION=eastasia

# Trigger.dev — dev mode 走 inlineDevEnqueue 不真发请求, 留空即可
TRIGGER_PROJECT_REF=proj_dev_placeholder
TRIGGER_SECRET_KEY=trigger-dev-placeholder-1234567890
TRIGGER_API_URL=http://localhost:3030

# P2 OpenRouter fallback — minimax 失败时的兜底. 留空 = 不启用 fallback.
OPENROUTER_API_KEY=
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
OPENROUTER_FALLBACK_MODEL=minimax/MiniMax-M3

# Creatomate template 自定义 (留空用内置 default)
CREATOMATE_TEMPLATE_ID=creatomate-builtin-30s-5beats
CREATOMATE_BASE_URL=https://api.creatomate.com/v2
CREATOMATE_POLL_MS=3000
CREATOMATE_POLL_TIMEOUT_MS=600000

# Human-in-Loop webhook (留空 = 撞墙仅入库 + log warn)
HUMAN_IN_LOOP_WEBHOOK_URL=

# P1 Toggle — RUN_TRIGGER_DEV 在 dev 走 inline 旁路 (lib/trigger.ts 已处理)
# ='0' 或 '1' 都行, dev 用 inline
RUN_TRIGGER_DEV=0
TRIGGER_DEPLOYMENT=cloud
EOF

echo "✅ .env.local 已生成 (含 schema-valid placeholder)."
echo ""
echo "下一步:"
echo "  1. npm run dev"
echo "  2. 浏览器 → http://localhost:3000"
echo "  3. 填 topic → 点开始生成 (server 启动 OK + auto-redirect 立即跳 polling 页)"
echo ""
echo "⚠️ 注意: dev 跑 pipeline 需要真 ANTHROPIC_API_KEY + CREATOMATE_API_KEY."
echo "  placeholder 'sk-ant-...' 会让 LLM real call 401. 真跑视频需要 user 提供"
echo "  自己 key. 或者**仅看 polling 页**看到哪里 fail."
